parameters:

services:
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Sf\DfKumueBundle\:
        resource: '../src/DfKumueBundle/*'
        #exclude: '../src/DfKumueBundle/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Sf\DfKumueBundle\Controller\:
        resource: '../src/DfKumueBundle/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
